### ISSUE TITLE
Simulation is distorted (is it in wgs84? ) 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CSL_Paris#5]
See 93d334b14b1e178b7f6a0514db19d6d748b39a12, the sim has what looks like Paris projection vs WGS84.

**Comment by RELNO** [comment]
![Screen Shot 2020-03-29 at 16 24 41](https://user-images.githubusercontent.com/14296774/77859872-dabeca00-71d9-11ea-9d90-e1a2c137fac5.png)

**Comment by agrignard** [comment]
this seems challenging indeed I really think the value should be read from the lat and long that are already projected modulo a conversion regarding the scale of your world and then the 3D model should adapt to this.

In _calcPosFromLatLonRad you try to make it to a 3D sphere but the value are already projected so I'm not sure it make sense to make this translation. I think it's more about finding the right scaling than doing this 3D mapping. this issue https://stackoverflow.com/questions/28365948/javascript-latitude-longitude-to-xyz-position-on-earth-threejs is to map on a sphere projected value but in our case we are proejecting on a flat surface (the table)

Is there a way to display in a debug mode the value in the opengl world of the 4 corner of the table? Then we can see how to make the transformation

If it can help this is the value in the 3D world (which is also an opengl world) in GAMA without the rotation as it might not help at the beginning to deal with the rotation

The value are in meter and I can easily export the agent value in this referential if it can help

<img width="1678" alt="Screen Shot 2020-03-29 at 23 42 47" src="https://user-images.githubusercontent.com/3928502/77861751-365b7880-7217-11ea-9950-8ee1d5451353.png">

**Comment by RELNO** [comment]
See https://github.com/CityScope/CSL_Paris/commit/d742c78c36ff30e5332e2577ebc81bd3a7d111c2, I've removed the spherical conversion, but the distortion seems to still be there

**Comment by RELNO** [comment]
![Screen Shot 2020-03-29 at 18 31 13](https://user-images.githubusercontent.com/14296774/77862750-7d337900-71eb-11ea-9b6f-a90d7d59d7b3.png)

The position is still off, but it's close enough to show that the circles are actually ovals

**Comment by RELNO** [comment]
![Screen Shot 2020-03-29 at 22 49 45](https://user-images.githubusercontent.com/14296774/77870559-baa9fd80-720f-11ea-9638-0548ab2c8064.png)

Fixed via Lat/Long in wgs84 to 2d conversion. still need to match scale, but on distortion.
For history sake: https://stackoverflow.com/questions/29761062/d3-mercator-geo-and-path-methods

**Comment by agrignard** [comment]
I would keep it open, as it is still not matching (there is a mix of scale and rotation still)

What if you try to draw a rectangle of 3624x3043 on top of the table? 
it should look like this 
<img width="1121" alt="Screen Shot 2020-03-30 at 10 54 20" src="https://user-images.githubusercontent.com/3928502/77893908-d7c4e780-7274-11ea-9691-64a0a82d298e.png">

**Comment by agrignard** [comment]
Also I think the current ratio is not exactly the same which has an impact on the mapping

What about keeping the real world dimension in the OpenGl World  I would then propose to replace this (I need to double-check if it's exactly this number but I'm 90% confident)
`````
const cubeGeo = new THREE.BoxBufferGeometry(3.5, 1, 2);
`````
by
`````
const cubeGeo = new THREE.BoxBufferGeometry(1.57, 0.6, 0.92);
`````
This is the size of the current model 1.57x92 
 Also then the 3D model fits in this table with a margin of 1cm so the footprint of the model should be 0.9x1.54, right now the margin is bigger which is also one reason for not havng the agent fitting exactly.

Then for the agent if we agree on this convention (having the real measure), it means the model is 1:2000 scale so I can totally give you from GAMA the real world position (equl to the exact OpenglWorld/2000 then and I think it should match perfectly)

**Comment by agrignard** [comment]
This what I have with 
`````
const cubeGeo = new THREE.BoxBufferGeometry(1.57, 0.6, 0.92);
`````
no mercator projection and sending the 3D world from GAMA it's gettig close, just a question of rotation now and offset but I think the mapping is the good one without distortion
<img width="901" alt="Screen Shot 2020-03-30 at 14 28 52" src="https://user-images.githubusercontent.com/3928502/77912574-12d61380-7293-11ea-92d4-bc91321cec6a.png">

and 
`````
let pnt = trips[i].path[time];
``````
instead of 
`````
let pnt = this._meractorProj(trips[i].path[time]);
`````

**Comment by RELNO** [comment]
> and

> let pnt = trips[i].path[time];
> instead of
> 
> let pnt = this._meractorProj(trips[i].path[time]);

Did you produce a different JSON to get there? I mean, do you scale already in GAMA?  If so for me it's better, since it's less computation per agent

**Comment by agrignard** [comment]
Fixed in https://github.com/CityScope/CSL_Paris/commit/52c253ad605254f26ea5f22778f0b5594f43bedd
